blog/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { sessions: 'users/sessions' }
  get 'welcome/index'
  
  
  resources :articles
  resources :tags, only: [:index, :show]

  resources :articles do
    resources :comments
  end

  root 'welcome#index'

end

blog/app/models/article.rb
	# == Schema Information
#
# Table name: articles
#
#  id         :integer          not null, primary key
#  title      :string
#  text       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  slug       :string
#

class Article < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]
  
  has_attached_file :poster, styles: { medium: "300x300>", thumb: "100x100>" },
  default_url: "/images/:style/missing.png"
  validates_attachment_content_type :poster, content_type: /\Aimage\/.*\Z/

  def should_generate_new_friendly_id?
		title_changed?
  end
  belongs_to :user

  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

#for adding tags
class Article < ActiveRecord::Base
  acts_as_taggable_on :tags
end

Article.tagged_with("rails")

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  http_basic_authenticate_with name: "akash", password: "secret", except: [:index, :show]
  load_and_authorize_resource
  #just checking

  def index

    #without pagination
    #@articles = Article.all

    #for pagination it is fetching pagination one by one
    #@articles = Article.paginate(:page => params[:page], :per_page => 3 )
    
    #for searching articles by name from collection page also
    @q = Article.ransack(params[:q])
    # @articles = @q.result(distinct: true).page(params[:page]).per_page(3)
    @articles = @q.result(distinct: true).includes(:tags).page(params[:page]).per_page(3)
    # or, use an explicit "per page" limit:
    #Post.paginate(:page => params[:page], :per_page => 30)

    ## render page links in the view: 
  end

  def show
    @article = Article.find(params[:id])
    authorize! :read, @article
  end

  def new
    @article = current_user.articles.build
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
 
    redirect_to articles_path
  end

  def edit
  @article = Article.find(params[:id])
  end
 
  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
  @article = Article.find(params[:id])
    if @article.update(article_params)
    redirect_to @article
    else
    render 'edit'
    end
  end

  private
  def article_params
    params.require(:article).permit(:title, :text, :tag_list,:poster)
  end
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/views/articles/_article.html.haml
%h2= link_to article.title, article_path(article)

blog/app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

blog/app/views/articles/_form.html.haml
= form_for @article, :html => { :class => "form-horizontal" } do |f|
  - if @article.errors.any?
    .panel.panel-danger
      .panel-heading
        %h3.panel-title
          = pluralize(@article.errors.count, "error")
          prohibited this article from being saved:
      .panel-body
        %ul
          - @article.errors.full_messages.each do |msg|
            %li= msg
  .form-group
    = f.label :title, :class => 'control-label col-md-1'
    .col-md-11
      = f.text_field :title, :class => 'form-control'
      = f.error_span(:title)
  .form-group
    = f.label :poster, 'Image', :class => 'control-label col-md-1'
    .col-md-11
      = f.file_field :poster
  .form-group
    = f.label :text, :class => 'control-label col-md-1'
    .col-md-11
      = f.text_area :text,:rows => '5', :class => 'form-control', :id => 'area1'
      = f.error_span(:text)
  .form-group
    = f.label :tag_list, 'Tags', :class => 'control-label col-md-1'
    .col-md-11
      = f.text_field :tag_list, :class => 'form-control', 'data-role'=>'tagsinput'
      = f.error_span(:tag_list)   
  .form-group
    .col-lg-offset-1.col-md-11
      = f.submit :class => 'btn btn-primary'
      = link_to 'Cancel',                          |
        articles_path, :class => 'btn btn-default' |


:javascript
  jQuery( document ).ready(function( $ ) {
    new nicEditor().panelInstance('area1');
  });

blog/app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

blog/app/views/articles/edit.html.haml
.row
  .col-xs-3.col-xs-offset-5	
    %h1 Edit articles_path
    = render 'form'
    = link_to 'Back', articles_path
    

blog/app/views/articles/index.html.erb
<%= javascript_include_tag "application" %>
<h1>Listing Articles</h1>
<%= link_to 'New article', new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>

    </tr>
  <% end %>
</table> 

blog/app/views/articles/index.html.haml
%nav.navbar.navbar-inverse
  .container-fluid
    %ul.nav.navbar-nav
      .navbar-header
        %a.navbar-brand{:href => "#"}
        = image_tag('logo1.gif',size: "50")
      %li.active
        = link_to "Home", root_path, method: :get ,class: "btn btn-primary"
      %li.active
        %a{:href => "/articles"} Collections
    %p.navbar-text.navbar-right
      =current_user.email
    %ul.nav.navbar-nav.navbar-right
      %li.active
        = link_to "Logout", destroy_user_session_path, method: :delete

= javascript_include_tag "application"
 
.add-article-container
  = link_to 'Add a New article', new_article_path, class: "btn btn-primary"

// to search from collections page also
= search_form_for @q, :url => url_for(:controller => 'articles', :action => 'index') do |f|
  = f.label :title_cont
  = f.search_field :title_cont
  = f.label :tags_name_cont
  = f.search_field :tags_name_cont
  = f.submit

= bootstrap_flash

.table-responsive
  %table.table.table-hover
    %tr
      %th= sort_link(@q, :title, 'Title', default_order: :asc)
      %th Text
      %th Tags
      %th= sort_link(@q, :created_at, 'Created_at', default_order: :asc)
      %th= sort_link(@q, :updated_at, 'Updated_at', default_order: :asc)
      %th{:colspan => "3"}
    - @articles.each do |article|
      %tr
        %td
          = article.title
        %td
          = article.text
        %td
          = render article.tags
        %td
          = article.created_at
        %td
          = article.updated_at
        %td
          = link_to 'Show', article_path(article)
        %td
          - if can? :update, article
            = link_to 'Edit', edit_article_path(article)
        %td
          - if can? :update, article
            = link_to 'Destroy', article_path(article), |
                method: :delete,                          |
                data: { confirm: 'Are you sure?' }        |

.add-article-container
  = will_paginate @articles, renderer: BootstrapPagination::Rails
            

blog/app/views/articles/new.html.erb
<h1>New article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

blog/app/views/articles/search_form.html.haml
= search_form_for @q do |f|
  = f.label :name_cont
  = f.search_field :name_cont
  = f.label :articles_title_start
  = f.search_field :articles_title_start
  = f.label :name_or_description_or_email_or_articles_title_cont
  = f.search_field :name_or_description_or_email_or_articles_title_cont
  = f.submit
  

blog/app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
 
<h2>Comments</h2>
<%= render @article.comments %>
 
<h2>Add a comment:</h2>
<%= render 'comments/form' %>
 
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

blog/app/views/articles/show.html.haml
.thumbnail
  .caption-full
    %h4
      = @article.title |
      %span.pull-right
        - if can? :update, @article
          = link_to 'Edit', edit_article_path(@article), :class => 'btn btn-primary' 
    %hr/
    = image_tag(@article.poster.url, :class => 'article-img img-responsive')
    %hr/   
    %p= @article.text.html_safe
  %p.pull-right
    %span.glyphicon.glyphicon-tags
    %span.btn.btn-default.btn-xs= raw @article.tags.map { |t| link_to t.name, tag_path(t.id) }.join(' | ')
  .ratings
    %p
      = time_ago_in_words(@article.created_at)
      ago
.well
  .text-right
    %h4 Comments
  %hr/
  = render @article.comments
.panel.panel-default
  .panel-heading.caption-full
    %p Leave a Comment
  .panel-body
    = render 'comments/form'
      
= link_to 'Back', articles_path, :class => 'btn btn-default'

%span.pull-right
  Written by 
  =current_user.email